In [1]:
print 'hello'

hello


In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pylab as plt
from sklearn.cross_validation import train_test_split



df = pd.read_csv('wine.csv', sep = ';')
X = df[list(df.columns)[:-1]]
y = df['quality']
X_train, X_test, y_train, y_test = train_test_split(X,y)


regressor = LinearRegression()
regressor.fit(X_train, y_train)
y_prediction = regressor.predict(X_test)
print 'R-squared', regressor.score(X_test,y_test)




R-squared 0.320639530846


32% of the variance in the test set is explained by the model


In [3]:
import pandas as pd
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LinearRegression

df = pd.read_csv('wine.csv', sep = ';')
X = df[list(df.columns)[:-1]]
y = df['quality']

regressor = LinearRegression()
scores = cross_val_score(regressor, X,y,cv=5 )
print scores.mean(), scores


0.290041628842 [ 0.13200871  0.31858135  0.34955348  0.369145    0.2809196 ]


5 times cross-validation. mean value is 29% This suggest this is a bettter value to use than 32%. 

In [4]:
corpus = [
    'UNC played Duke in basketball',
    'Duke lost the basketball game'   
    
]

8 unique words, this is the vocabulary. each  word isgiven a binary value.

UNC is the first element and present in the first document = 1

game is not present in the first document so = 0



In [6]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'UNC played Duke in basketball',
    'Duke lost the basketball game'      
]

vectorizer = CountVectorizer()
print vectorizer.fit_transform(corpus).todense()
print vectorizer.vocabulary_


[[1 1 0 1 0 1 0 1]
 [1 1 1 0 1 0 1 0]]
{u'duke': 1, u'basketball': 0, u'lost': 4, u'played': 5, u'game': 2, u'unc': 7, u'in': 3, u'the': 6}


top row of binary, 1 or 0 for unquie words. prder respesented by number after words.

same with bottom row, compaire each unquie word with word in that document.

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'UNC played Duke in basketball',
    'Duke lost the basketball game' ,
    'I ate a Sandwich'
]

vectorizer = CountVectorizer()
print vectorizer.fit_transform(corpus).todense()
print vectorizer.vocabulary_


[[0 1 1 0 1 0 1 0 0 1]
 [0 1 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 0 0 1 0 0]]
{u'duke': 2, u'basketball': 1, u'lost': 5, u'played': 6, u'in': 4, u'game': 3, u'sandwich': 7, u'unc': 9, u'ate': 0, u'the': 8}


now have ten unique words AND last document clearly has less in common than first two

In [17]:
from sklearn.metrics.pairwise import euclidean_distances
counts = [
     [0, 1, 1, 0, 1, 0, 1, 0, 0, 1],
     [0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
     [1, 0, 0, 0, 0, 0, 0, 1, 0 ,0]       
]

print 'Distance between 1st and 2nd documents:', euclidean_distances(counts[0], counts[1])
print 'Distance between 1st and 3nd documents:', euclidean_distances(counts[0], counts[2])
print 'Distance between 2nd and 3rd documents:', euclidean_distances(counts[1], counts[2])


Distance between 1st and 2nd documents: [[ 2.44948974]]
Distance between 1st and 3nd documents: [[ 2.64575131]]
Distance between 2nd and 3rd documents: [[ 2.64575131]]


C:\Python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Python27\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Python27\lib\site-packages\sklearn